FROM centos:7.4.1708
USER root

# Install required system packages.
RUN yum install -y \
		python \
		python-pip \
		python-virtualenv \
    python-boto \
    python-boto3 \
		gcc \
		python-devel \
		openssl-devel \
		openssh-clients \
		git \
    ansible \
	;
